Revert "fix commands: remove function"
This reverts commit bc9c60d51b791bc304996663890af77723df0973.

diff --git a/commands/gcccompile b/commands/gcccompile
--- a/commands/gcccompile
+++ b/commands/gcccompile
@@ -1,4 +1,4 @@
-#!/bin/zsh
+#! /bin/zsh
 
 # gcccompile
 # --------------
@@ -6,15 +6,17 @@
 # Created at : 2026.05.07
 # Updated at : 2026.05.07
 
-if [[ -f "$1" ]]; then
-  # 入力ファイル名から拡張子を除いたものに .out をつける
-  local output="${1%.*}.out"
-  gcc "$1" -o "$output"
+gcccompile() {
+  if [[ -f "$1" ]]; then
+    # 入力ファイル名から拡張子を除いたものに .out をつける
+    local output="${1%.*}.out"
+    gcc "$1" -o "$output"
     
-  # コンパイル成功時のみメッセージを表示
-  if [[ $? -eq 0 ]]; then
-    echo "Compiled: $1 -> $output"
+    # コンパイル成功時のみメッセージを表示
+    if [[ $? -eq 0 ]]; then
+      echo "Compiled: $1 -> $output"
+    fi
+  else
+    echo "Error: File '$1' not found."
   fi
-else
-  echo "Error: File '$1' not found."
-fi
+}
diff --git a/commands/grg b/commands/grg
--- a/commands/grg
+++ b/commands/grg
@@ -1,4 +1,4 @@
-#!/bin/zsh
+#! /bin/zsh
 
 # grg commands
 # --------------
@@ -6,43 +6,46 @@
 # Created at : 2026.06.08
 # Updated at : 2026.06.08
 
-local OPTIND
-local selected dir
-local lsopts="-la"
+grg() {
+  local OPTIND
+  local selected dir
+  local lsopts="-la"
   
-while [ $# -gt 0 ]; do
-  case "$1" in
-    -h|--help)
-      sed 's/^      //' <<< "Usage: grg [OPTIONS]
-      Options:
-        -c, --compact   Compact mode
-        -h, --help      Show this help
-      "
-      return 0
-      ;;
-    -c|--compact)
-      lsopts=""
-      shift
-      ;;
-    -*)
-      echo "grg: invalid option -- '$1'"
-      return 1
-      ;;
-    *)
-      break
-      ;;
-  esac
-done
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      -h|--help)
+        sed 's/^        //' <<< "Usage: grg [OPTIONS]
 
-selected=$(ghq list | sed 's|^github.com/||' \
-  | fzf --layout=reverse --border \
-        --preview 'ls '"$lsopts"' "$(ghq root)/github.com/"{}')
+        Options:
+          -c, --compact   Compact mode
+          -h, --help      Show this help
+        "
+        return 0
+        ;;
+      -c|--compact)
+        lsopts=""
+        shift
+        ;;
+      -*)
+        echo "grg: invalid option -- '$1'"
+        return 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+  done
 
-[ -n "$selected" ] || return
+  selected=$(ghq list | sed 's|^github.com/||' \
+    | fzf --layout=reverse --border \
+          --preview 'ls '"$lsopts"' "$(ghq root)/github.com/"{}')
 
-dir=$(ghq list -p "github.com/$selected")
-[ -d "$dir" ] || return
+  [ -n "$selected" ] || return
 
-cd "$dir" || return
+  dir=$(ghq list -p "github.com/$selected")
+  [ -d "$dir" ] || return
 
-pwd
+  cd "$dir" || return
+
+  pwd
+}
